Algoritmo "ANTECESSOR"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
num01: inteiro
valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero:")
leia(num01)
valor<- num01 - 1
escreva("O antecessor é: ", valor)

Fimalgoritmo