Algoritmo "AREA QUADRADO"
//  
//  
// 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
base: inteiro
altura: inteiro
valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um valor:")
leia(base)
escreva("Digite outro valor:")
leia(altura)
valor<- base * altura
escreva("A area do circulo é: ", valor)

Fimalgoritmo