Algoritmo "EX018"
// logica de progamação
// Jailson
// Descrição   : Ler um valor e escrever se é positivo ou negativo (considere o valor zero como positivo).
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08/2021
Var

   valor : inteiro

Inicio

   Escreva("Digite um valor: ")
   Leia(valor)
   se (valor >= 0) entao
      Escreva("O valor é positivo! ")
   senao
      Escreva("O valor é negativo! ")

   fimse
Fimalgoritmo