Algoritmo "Exercicio07"
//
//
// Descrição : Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a área do retângulo.
// Autor(a) : Lucas
// Data atual : 24/08/2021
Var
// Seção de Declarações das variáveis
raio,area:real

Inicio

Escreval("Digite o valor do raio do círculo:")
Leia (raio)
area<-raio*raio*pi
Escreva("O valor da area do círculo corresponde a : ",area, "cm²")

Fimalgoritmo