Algoritmo "exibir mensagem"
// 
// Discilplina : [logica de programação e js]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("lucas - sp")
escreval("equipa 04 a melhor")
escreva ("
Fimalgoritmo