Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
num01: inteiro
num02: inteiro
soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um numero:")
leia(num01)
escreva("digite um numero")
leia(num02)
soma<-num01 + num02
escreva("a soma é: ", soma)

Fimalgoritmo